nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] # or whatever your frontend port is
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
            max_age: 3600